package langs

var Langs map[string]string = map[string]string{
	"English":    "gb",
	"Spanish":    "es",
	"French":     "fr",
	"Korean":     "kr",
	"Chinese":    "cn",
	"German":     "de",
	"Portuguese": "pt",
	"Turkish":    "tr",
	"Indonesian": "id",
	"Japanese":   "jp",
	"Greek":      "gr",
	"Filipino":   "ph",
	"Italian":    "it",
	"Polish":     "pl",
	"Thai":       "th",
	"Malay":      "my",
	"Hungarian":  "hu",
	"Romanian":   "ro",
	"Arabic":     "sa",
	"Hebrew":     "il",
	"Russian":    "ru",
	"Vietnamese": "vn",
	"Dutch":      "nl",
	"Bengali":    "bd",
	"Persian":    "af",
	"Czech":      "cz",
	"Brazilian":  "br",
	"Bulgarian":  "bg",
	"Danish":     "dk",
	"Swedish":    "se",
	"Lithuanian": "lt",
	"Other":      "other",
}
